// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJSd3qk1UuX1lfQuz0-n5yPw0UcSvJ1Uw',
    appId: '1:836333937912:web:4dd84001eeb3542056070d',
    messagingSenderId: '836333937912',
    projectId: 'appointment-app-59053',
    authDomain: 'appointment-app-59053.firebaseapp.com',
    storageBucket: 'appointment-app-59053.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwqNoBpFM9fxJnWnMHuBgvFYWXghpiRDs',
    appId: '1:836333937912:android:59ce22b47692cc9a56070d',
    messagingSenderId: '836333937912',
    projectId: 'appointment-app-59053',
    storageBucket: 'appointment-app-59053.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIw1ESmz9qd-m44u8aA6yp9ipRKzTshXo',
    appId: '1:836333937912:ios:7a521355db7a3b7356070d',
    messagingSenderId: '836333937912',
    projectId: 'appointment-app-59053',
    storageBucket: 'appointment-app-59053.firebasestorage.app',
    iosBundleId: 'com.example.patronBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIw1ESmz9qd-m44u8aA6yp9ipRKzTshXo',
    appId: '1:836333937912:ios:7a521355db7a3b7356070d',
    messagingSenderId: '836333937912',
    projectId: 'appointment-app-59053',
    storageBucket: 'appointment-app-59053.firebasestorage.app',
    iosBundleId: 'com.example.patronBloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJSd3qk1UuX1lfQuz0-n5yPw0UcSvJ1Uw',
    appId: '1:836333937912:web:441dcb9f8768f85056070d',
    messagingSenderId: '836333937912',
    projectId: 'appointment-app-59053',
    authDomain: 'appointment-app-59053.firebaseapp.com',
    storageBucket: 'appointment-app-59053.firebasestorage.app',
  );

}